export const FETCHING_SHOUTS = "FETCHING_SHOUTS";
export const FETCHING_SHOUTS_SUCCESS = "FETCHING_SHOUTS_SUCCESS";
export const FETCHING_SHOUTS_FAILED = "FETCHING_SHOUTS_FAILED";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

