export const types = {

    FETCH_SHOUTS: "FETCH_SHOUTS",
    FETCH_USER_DETAILS: "FETCH_USER_DETAILS",
    LOGIN_REQUESTED: "LOGIN_REQUESTED",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    SIGNUP_REQUESTED: "SIGNUP_REQUESTED",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILED: "SIGNUP_FAILED",
}


